version: '3.4'

services:
  miner:
    image: andersonpids/bitcoin-nicehash-miner
    env_file:
      - ./config.env
    restart: always
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.75'
